apiVersion: apps/v1
kind: Deployment
metadata:
  name: cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cd
  template:
    metadata:
      labels:
        app: cd
    spec:
      containers:
        - name: cd
          image: cd:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: cd
spec:
  selector:
    app: cd
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP